# Generated by Django 5.2 on 2025-05-06 12:59

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("mainApp", "0008_candidate_certificate_candidate_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[],
            options={
                "ordering": "",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
